#!/usr/bin/env node
// Benchmark runner. `--gates` runs the P1–P5 gate subset and regenerates
// BENCHMARKS.md (BRIEF §8). Real benchmark implementations land in M6; until
// then this emits the environment block and an explicit not-yet-implemented
// marker (numbers only ever come from runner output, §21).
import { execSync } from "node:child_process";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";

const REPO = path.resolve(path.dirname(new URL(import.meta.url).pathname), "..");
const gatesOnly = process.argv.includes("--gates");

function tryExec(cmd) {
  try {
    return execSync(cmd, { encoding: "utf8" }).trim();
  } catch {
    return "unknown";
  }
}

export function envBlock() {
  const chip = tryExec("sysctl -n machdep.cpu.brand_string");
  const cores = os.cpus().length;
  const mem = `${Math.round(os.totalmem() / 1024 ** 3)} GB`;
  const macos = tryExec("sw_vers -productVersion");
  const chrome = tryExec(
    '"/Applications/Google Chrome.app/Contents/MacOS/Google Chrome" --version 2>/dev/null',
  );
  const node = process.version;
  const pnpmv = tryExec("pnpm --version");
  const refVersion = "pysubgroup 0.9.0 (reference/uv.lock)";
  return [
    "## Environment",
    "",
    `- chip: ${chip} (${cores} cores, ${mem})`,
    `- macOS: ${macos}`,
    `- chrome: ${chrome}`,
    `- node: ${node}, pnpm: ${pnpmv}`,
    `- reference: ${refVersion}`,
    `- date: ${new Date().toISOString()}`,
    "",
  ].join("\n");
}

const header =
  "# BENCHMARKS.md — performance report\n\nGenerated by `pnpm bench:gates`. Do not edit by hand.\n\n";
const body = `${header}${envBlock()}\n## Gates\n\nBenchmark runner not yet implemented (lands in M6). No performance gates evaluated.\n`;

fs.writeFileSync(path.join(REPO, "BENCHMARKS.md"), body);
console.log(
  `bench${gatesOnly ? ":gates" : ""}: BENCHMARKS.md regenerated (M6 pending — no gates evaluated yet)`,
);
