#!/usr/bin/env node
// Assembles PARITY.md from the machine-written gate rows in .gate/rows/ and
// cross-checks COMPATIBILITY.md adjudications against recorded divergences
// (BRIEF §6.5). Never hand-edit PARITY.md — it is regenerated by `pnpm gate`.
import fs from "node:fs";
import path from "node:path";

export const REPO = path.resolve(path.dirname(new URL(import.meta.url).pathname), "..");
const GATE_DIR = path.join(REPO, ".gate");

export function readRows() {
  const dir = path.join(GATE_DIR, "rows");
  if (!fs.existsSync(dir)) return [];
  const rows = [];
  for (const f of fs.readdirSync(dir).sort()) {
    if (!f.endsWith(".json")) continue;
    rows.push(JSON.parse(fs.readFileSync(path.join(dir, f), "utf8")));
  }
  return rows;
}

export function readDivergences() {
  const f = path.join(GATE_DIR, "divergences.json");
  if (!fs.existsSync(f)) return [];
  return JSON.parse(fs.readFileSync(f, "utf8"));
}

export function adjudicationIds() {
  const f = path.join(REPO, "COMPATIBILITY.md");
  if (!fs.existsSync(f)) return new Set();
  const text = fs.readFileSync(f, "utf8");
  return new Set([...text.matchAll(/^###\s+(ADJ-[A-Za-z0-9_-]+)/gm)].map((m) => m[1]));
}

export function assemble() {
  const rows = readRows();
  const divergences = readDivergences();
  const adjIds = adjudicationIds();

  // Adjudication integrity: every divergence the differential runner found
  // must cite an adjudication that exists in COMPATIBILITY.md.
  const unadjudicated = divergences.filter((d) => !d.adjudication || !adjIds.has(d.adjudication));
  rows.push({
    id: "differential-adjudication",
    cell: "all-differential",
    check: "unadjudicated divergences",
    value: String(unadjudicated.length),
    expected: "0",
    gate: true,
    pass: unadjudicated.length === 0,
    adj: "",
  });

  const gateRows = rows.filter((r) => r.gate);
  const passCount = gateRows.filter((r) => r.pass).length;
  const allPass = passCount === gateRows.length;

  const lines = [];
  lines.push("# PARITY.md — gate report");
  lines.push("");
  lines.push(`Generated by \`pnpm gate\` on ${new Date().toISOString()}. Do not edit by hand.`);
  lines.push("");
  lines.push("| id | cell | check | value | expected | GATE | ADJ | verdict |");
  lines.push("|---|---|---|---|---|---|---|---|");
  for (const r of rows.sort((a, b) => (a.id < b.id ? -1 : a.id > b.id ? 1 : 0))) {
    lines.push(
      `| ${r.id} | ${r.cell} | ${r.check} | ${r.value} | ${r.expected} | ${r.gate ? "GATE" : "info"} | ${
        r.adj || ""
      } | ${r.pass ? "PASS" : "FAIL"} |`,
    );
  }
  lines.push("");
  lines.push(`**${passCount}/${gateRows.length} gates pass.**`);
  lines.push("");
  const parity = lines.join("\n");
  fs.writeFileSync(path.join(REPO, "PARITY.md"), parity);

  const compatSummary = summarizeCompat(divergences, adjIds, unadjudicated);
  return { parity, compatSummary, allPass, passCount, gateCount: gateRows.length, unadjudicated };
}

export function summarizeCompat(divergences, adjIds, unadjudicated) {
  const cited = new Set(divergences.map((d) => d.adjudication).filter(Boolean));
  const lines = [];
  lines.push("COMPATIBILITY summary:");
  lines.push(
    `  adjudications in COMPATIBILITY.md : ${adjIds.size}${adjIds.size ? ` (${[...adjIds].sort().join(", ")})` : ""}`,
  );
  lines.push(`  divergences found by runner       : ${divergences.length}`);
  lines.push(`  cited adjudications               : ${cited.size}`);
  lines.push(`  UNADJUDICATED divergences         : ${unadjudicated.length}`);
  for (const d of unadjudicated.slice(0, 10)) {
    lines.push(`    ! ${d.cell ?? d.id}: ${d.summary ?? JSON.stringify(d).slice(0, 160)}`);
  }
  return lines.join("\n");
}

if (process.argv[1] && import.meta.url.endsWith(path.basename(process.argv[1]))) {
  const { parity, compatSummary, allPass } = assemble();
  console.log(parity);
  console.log(compatSummary);
  process.exit(allPass ? 0 : 1);
}
