/**
 * The §6.2 exactness matrix (BRIEF §6.4 configs): every cell is run through
 * every exact algorithm × pruning on/off and compared to the exhaustive
 * oracle's top-k EXACTLY. Broader than the differential matrix — synthetic
 * tie/NA/duplicate stress cells and QF configs with no reference fixture
 * (GA, combined, median, tscore, EMM) are exactness-only.
 */
import type { CellSpec } from "../util/cells.js";

export const EXACTNESS_CELLS: CellSpec[] = [
  // --- Reference-dataset binary cells across QF families and depths
  {
    id: "x-titanic-wracc-d2-k5",
    dataset: "titanic",
    target: { type: "binary", attribute: "Survived", value: 1 },
    space: { ignore: ["Survived"], nbins: 5 },
    qf: { name: "wracc" },
    depth: 2,
    k: 5,
    minQuality: 0,
  },
  {
    id: "x-titanic-wracc-d1-k1",
    dataset: "titanic",
    target: { type: "binary", attribute: "Survived", value: 1 },
    space: { ignore: ["Survived"], nbins: 5 },
    qf: { name: "wracc" },
    depth: 1,
    k: 1,
    minQuality: 0,
  },
  {
    id: "x-titanic-simpleBinomial-d3-k10",
    dataset: "titanic",
    target: { type: "binary", attribute: "Survived", value: 1 },
    space: { ignore: ["Survived", "PassengerId", "Name", "Ticket", "Cabin"], nbins: 2 },
    qf: { name: "simpleBinomial" },
    depth: 3,
    k: 10,
    minQuality: 0,
  },
  {
    id: "x-titanic-chi2-d2-k10",
    dataset: "titanic",
    target: { type: "binary", attribute: "Survived", value: 1 },
    space: { ignore: ["Survived"], nbins: 5 },
    qf: { name: "chiSquared", direction: "both", minInstances: 5, stat: "chi2" },
    depth: 2,
    k: 10,
    minQuality: 0,
  },
  {
    id: "x-titanic-chi2-pvalue-negative-d2-k10",
    dataset: "titanic",
    target: { type: "binary", attribute: "Survived", value: 1 },
    space: { ignore: ["Survived", "PassengerId", "Name", "Ticket", "Cabin"], nbins: 5 },
    qf: { name: "chiSquared", direction: "negative", minInstances: 5, stat: "pValue" },
    depth: 2,
    k: 10,
    minQuality: Number.NEGATIVE_INFINITY,
  },
  {
    id: "x-titanic-standard2-d2-k10",
    // a = 2: estimate exists but pruningSafe = false — no-prune path with
    // an estimate present (spec §6.1 admissibility bound is a ≤ 1).
    dataset: "titanic",
    target: { type: "binary", attribute: "Survived", value: 1 },
    space: { ignore: ["Survived"], nbins: 5 },
    qf: { name: "standard", a: 2 },
    depth: 2,
    k: 10,
    minQuality: 0,
  },
  {
    id: "x-titanic-lift-minsupport-d2-k10",
    dataset: "titanic",
    target: { type: "binary", attribute: "Survived", value: 1 },
    space: { ignore: ["Survived"], nbins: 5 },
    qf: { name: "lift" },
    depth: 2,
    k: 10,
    minQuality: 0,
    constraints: [{ type: "minSupport", count: 30 }],
  },
  {
    id: "x-titanic-wracc-minquality-d2-k10",
    dataset: "titanic",
    target: { type: "binary", attribute: "Survived", value: 1 },
    space: { ignore: ["Survived"], nbins: 5 },
    qf: { name: "wracc" },
    depth: 2,
    k: 10,
    minQuality: 0.005,
  },
  {
    id: "x-titanic-wracc-nbins10-allsel-d2-k10",
    dataset: "titanic",
    target: { type: "binary", attribute: "Survived", value: 1 },
    space: {
      ignore: ["Survived", "PassengerId", "Name", "Ticket", "Cabin"],
      nbins: 10,
      intervalsOnly: false,
    },
    qf: { name: "wracc" },
    depth: 2,
    k: 10,
    minQuality: 0,
  },
  {
    id: "x-creditg-wracc-negations-d2-k10",
    dataset: "credit-g",
    target: { type: "binary", attribute: "class", value: "bad" },
    space: { ignore: ["class"], nominalOnly: true, negations: true },
    qf: { name: "wracc" },
    depth: 2,
    k: 10,
    minQuality: 0,
  },
  // --- Numeric-target cells across estimators / a / invert / centroid
  {
    id: "x-creditg-stdnum-sum-d2-k10",
    dataset: "credit-g",
    target: { type: "numeric", attribute: "age" },
    space: { ignore: ["age", "class"], nbins: 5 },
    qf: { name: "standardNumeric", a: 1, estimator: "sum" },
    depth: 2,
    k: 10,
    minQuality: 0,
  },
  {
    id: "x-creditg-stdnum-average-d2-k10",
    dataset: "credit-g",
    target: { type: "numeric", attribute: "age" },
    space: { ignore: ["age", "class"], nbins: 5 },
    qf: { name: "standardNumeric", a: 1, estimator: "average" },
    depth: 2,
    k: 10,
    minQuality: 0,
  },
  {
    id: "x-creditg-stdnum-order-d2-k10",
    dataset: "credit-g",
    target: { type: "numeric", attribute: "age" },
    space: { ignore: ["age", "class"], nbins: 5 },
    qf: { name: "standardNumeric", a: 1, estimator: "order" },
    depth: 2,
    k: 10,
    minQuality: 0,
  },
  {
    id: "x-creditg-stdnum-a05-invert-d2-k10",
    dataset: "credit-g",
    target: { type: "numeric", attribute: "age" },
    space: { ignore: ["age", "class"], nbins: 5 },
    qf: { name: "standardNumeric", a: 0.5, invert: true },
    depth: 2,
    k: 10,
    minQuality: 0,
  },
  // --- FI target
  {
    id: "x-creditg-fi-count-d2-k10",
    dataset: "credit-g",
    target: { type: "fi" },
    space: { ignore: ["class"], nbins: 5 },
    qf: { name: "count" },
    depth: 2,
    k: 10,
    minQuality: 0,
  },
  {
    id: "x-creditg-fi-area-d2-k10",
    dataset: "credit-g",
    target: { type: "fi" },
    space: { ignore: ["class"], nbins: 5 },
    qf: { name: "area" },
    depth: 2,
    k: 10,
    minQuality: 0,
  },
  // --- EMM (depth 1: O(N) per candidate by construction)
  {
    id: "x-creditg-emm-d1-k5",
    dataset: "credit-g",
    target: { type: "emm", x: "duration", y: "credit_amount" },
    space: { ignore: ["duration", "credit_amount", "class"], nominalOnly: true },
    qf: { name: "emmLikelihood", x: "duration", y: "credit_amount" },
    depth: 1,
    k: 5,
    minQuality: Number.NEGATIVE_INFINITY,
  },
  // --- Description-level QFs (GA family, combined)
  {
    id: "x-titanic-ga-wracc-d2-k8",
    dataset: "titanic",
    target: { type: "binary", attribute: "Survived", value: 1 },
    space: { ignore: ["Survived", "PassengerId", "Name", "Ticket", "Cabin"], nbins: 3 },
    qf: { name: "generalizationAware", inner: { name: "wracc" } },
    depth: 2,
    k: 8,
    minQuality: 0,
  },
  {
    id: "x-titanic-gastandard-d2-k8",
    dataset: "titanic",
    target: { type: "binary", attribute: "Survived", value: 1 },
    space: { ignore: ["Survived", "PassengerId", "Name", "Ticket", "Cabin"], nbins: 3 },
    qf: { name: "gaStandard", a: 0.5 },
    depth: 2,
    k: 8,
    minQuality: 0,
  },
  {
    id: "x-titanic-combined-d2-k8",
    dataset: "titanic",
    target: { type: "binary", attribute: "Survived", value: 1 },
    space: { ignore: ["Survived", "PassengerId", "Name", "Ticket", "Cabin"], nbins: 3 },
    qf: {
      name: "combined",
      members: [
        { qf: { name: "wracc" }, weight: 0.7 },
        { qf: { name: "simpleBinomial" }, weight: 0.3 },
      ],
    },
    depth: 2,
    k: 8,
    minQuality: 0,
  },
  // --- Planted synthetics
  {
    id: "x-planted-binary-500-wracc-d2-k5",
    dataset: "synth:planted-binary-500",
    target: { type: "binary", attribute: "y", value: 1 },
    space: { ignore: ["y"] },
    qf: { name: "wracc" },
    depth: 2,
    k: 5,
    minQuality: 0,
  },
  {
    id: "x-planted-numeric-500-stdnum-d2-k5",
    dataset: "synth:planted-numeric-500",
    target: { type: "numeric", attribute: "t" },
    space: { ignore: ["t"] },
    qf: { name: "standardNumeric", a: 1 },
    depth: 2,
    k: 5,
    minQuality: 0,
  },
  // --- Tie stress: k cuts inside tie groups; k beyond the space
  {
    id: "x-tie-stress-wracc-d3-k10",
    dataset: "synth:tie-stress",
    target: { type: "binary", attribute: "y", value: 1 },
    space: { ignore: ["y"] },
    qf: { name: "wracc" },
    depth: 3,
    k: 10,
    minQuality: Number.NEGATIVE_INFINITY,
  },
  {
    id: "x-tie-stress-wracc-d3-k100",
    dataset: "synth:tie-stress",
    target: { type: "binary", attribute: "y", value: 1 },
    space: { ignore: ["y"] },
    qf: { name: "wracc" },
    depth: 3,
    k: 100,
    minQuality: Number.NEGATIVE_INFINITY,
  },
  {
    id: "x-tie-stress-count-d2-k20",
    dataset: "synth:tie-stress",
    target: { type: "fi" },
    space: { ignore: [] },
    qf: { name: "count" },
    depth: 2,
    k: 20,
    minQuality: Number.NEGATIVE_INFINITY,
  },
  // --- NA stress (incl. negation-over-NA, numeric target with NA columns)
  {
    id: "x-na-stress-wracc-negations-d2-k10",
    dataset: "synth:na-stress",
    target: { type: "binary", attribute: "y", value: 1 },
    space: { ignore: ["y", "t", "x2"], negations: true },
    qf: { name: "wracc" },
    depth: 2,
    k: 10,
    minQuality: Number.NEGATIVE_INFINITY,
  },
  {
    id: "x-na-stress-stdnum-d2-k10",
    dataset: "synth:na-stress",
    target: { type: "numeric", attribute: "t" },
    space: { ignore: ["t", "y"], nbins: 5 },
    qf: { name: "standardNumeric", a: 1 },
    depth: 2,
    k: 10,
    minQuality: 0,
  },
  {
    id: "x-na-stress-median-d2-k8",
    dataset: "synth:na-stress",
    target: { type: "numeric", attribute: "t" },
    space: { ignore: ["t", "y"], nbins: 5 },
    qf: { name: "standardNumericMedian", a: 1 },
    depth: 2,
    k: 8,
    minQuality: 0,
  },
  {
    id: "x-na-stress-tscore-d2-k8",
    dataset: "synth:na-stress",
    target: { type: "numeric", attribute: "t" },
    space: { ignore: ["t", "y"], nbins: 5 },
    qf: { name: "standardNumericTscore" },
    depth: 2,
    k: 8,
    minQuality: 0,
  },
  // --- Duplicate-row stress
  {
    id: "x-dup-rows-wracc-d3-k10",
    dataset: "synth:dup-rows",
    target: { type: "binary", attribute: "y", value: 1 },
    space: { ignore: ["y"], nbins: 5 },
    qf: { name: "wracc" },
    depth: 3,
    k: 10,
    minQuality: Number.NEGATIVE_INFINITY,
  },
  {
    id: "x-dup-rows-area-d2-k10",
    dataset: "synth:dup-rows",
    target: { type: "fi" },
    space: { ignore: ["y"], nbins: 5 },
    qf: { name: "area" },
    depth: 2,
    k: 10,
    minQuality: 0,
  },
];

/** Fast subset for gate:quick (one per structural family). */
export const QUICK_CELL_IDS = [
  "x-titanic-wracc-d2-k5",
  "x-creditg-stdnum-sum-d2-k10",
  "x-tie-stress-wracc-d3-k10",
  "x-na-stress-wracc-negations-d2-k10",
];
